# Generated by Django 4.2.3 on 2023-07-19 18:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_auto', models.CharField(max_length=50)),
                ('transmisson', models.CharField(choices=[('MANUAL', 'MANUAL'), ('ROBOTIC', 'ROBOTIC'), ('ROBOTIC', 'ROBOTIC'), ('VARIABLE', 'VARIABLE')], max_length=100)),
                ('type_of_body', models.CharField(choices=[('Sedan', 'Sedan'), ('Limousine', 'Limousine'), ('Pickup', 'Pickup'), ('Hatchback', 'Hatchback'), ('Station Wagon', 'Station Wagon'), ('Liftback', 'Liftback'), ('Minivan', 'Minivan'), ('Coupe', 'Coupe'), ('Cabriolet', 'Cabriolet'), ('Roadster', 'Roadster'), ('Bodies out of classification', 'Bodies out of classification')], max_length=100)),
                ('produced_in', models.IntegerField(validators=[django.core.validators.MinValueValidator(1899), django.core.validators.MaxValueValidator(2023)])),
                ('distance_km', models.IntegerField()),
                ('type_of_the_body', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
