# Generated by Django 4.2.3 on 2023-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autos',
            name='type_of_the_body',
        ),
        migrations.AlterField(
            model_name='autos',
            name='transmisson',
            field=models.CharField(choices=[('MANUAL', 'MANUAL'), ('ROBOTIC', 'ROBOTIC'), ('VARIABLE', 'VARIABLE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='autos',
            name='type_of_body',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Limousine', 'Limousine'), ('Pickup', 'Pickup'), ('Hatchback', 'Hatchback'), ('Station Wagon', 'Station Wagon'), ('Liftback', 'Liftback'), ('Minivan', 'Minivan'), ('Coupe', 'Coupe'), ('Cabriolet', 'Cabriolet'), ('Roadster', 'Roadster'), ('Bodies out of classification', 'Bodies out of classification')], max_length=100, null=True),
        ),
    ]
