# Generated by Django 4.2.2 on 2023-07-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_accounts_remove_user_groups_and_more'),
        ('autos', '0002_remove_autos_type_of_the_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.accounts'),
        ),
    ]
