# Generated by Django 4.2.3 on 2023-07-19 17:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_auto', models.CharField(max_length=50)),
                ('produced_in', models.IntegerField(validators=[django.core.validators.MinValueValidator(1899), django.core.validators.MaxValueValidator(2023)])),
                ('distance_km', models.IntegerField()),
                ('type_of_the_body', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
