# Generated by Django 4.2.2 on 2023-07-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='pasword',
            new_name='password',
        ),
        migrations.AddField(
            model_name='accounts',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
